settings:
  title: 'System Status'
  url: 'https://status.devo.plus' # used for Slack messages
  logo: logo.png # image in ./public/ folder
  daysInHistogram: 180 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: lb-devoplus-com-tr
    name: Devoplus Load Balancer
    url: 'https://lb.devoplus.com.tr/'
    method: GET
    expectStatus: 200
    linkable: false
    followRedirect: false

  - id: api-devoplus-com-tr
    name: Devoplus API
    url: 'https://api.devoplus.com.tr/'
    method: GET
    expectStatus: 401
    linkable: false
    followRedirect: false

  - id: portal-devoplus-com-tr
    name: Devoplus Portal
    url: 'https://portal.devoplus.com.tr/'
    method: GET
    expectStatus: 200
    linkable: false
    followRedirect: false

  - id: sso-devoplus-com-tr
    name: Devoplus SSO
    url: 'https://sso.devoplus.com.tr/'
    method: GET
    expectStatus: 200
    linkable: false
    followRedirect: false

  - id: url-shortener
    name: URL Shortener Service
    url: 'https://dvp.ls/'
    method: GET
    expectStatus: 200
    linkable: false
    followRedirect: true

  - id: web-site
    name: Devoplus Web Site
    url: 'https://www.devoplus.com.tr/'
    method: GET
    expectStatus: 200
    linkable: false
    followRedirect: false
